"""Resolving reconstruction inputs: a local directory or an S3 data asset.

S3 is the citable form -- an exaSPIM reconstruction asset URI identifies the
reconstructions exactly -- so figures made from one can be regenerated by
anyone with read access, without passing files around.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path
from urllib.parse import urlparse

from . import atlas

SWC_SUBDIR = "ccf_space_reconstructions/swc"
"""Where CCF-space SWCs sit inside an exaSPIM reconstruction asset."""

SWC_SUBDIR_ALIASES = (
    "ccf_space_reconstructions/swc",
    "ccf_space_reconstructions/swcs",
    "final/ccf_space_reconstructions/swc",
    "final/ccf_space_reconstructions/swcs",
)
"""Spellings seen across assets. Both `swc` and `swcs` occur, and processed
assets nest the whole thing under `final/`."""

_ASSET = re.compile(r"^(?P<modality>\w+)_(?P<subject>\d+)_(?P<acquired>[\d\-_]+?)"
                    r"_reconstructions_(?P<made>[\d\-_]+)$")


@dataclass(frozen=True)
class Source:
    """A resolved set of SWC files and where they came from."""

    uri: str
    local: Path
    files: list[Path]

    @property
    def asset_name(self) -> str:
        """Asset directory name, for provenance; the local stem if not S3."""
        return self.uri.rstrip("/").rsplit("/", 1)[-1]

    @property
    def subject(self) -> str | None:
        """Subject id parsed from an exaSPIM asset name, when recognisable."""
        found = _ASSET.match(self.asset_name)
        return found.group("subject") if found else None


def resolve(uri: str, subdir: str | None = SWC_SUBDIR,
            dest: Path | None = None, unsigned: bool = True) -> Source:
    """Return the SWC files for `uri`, downloading from S3 if needed.

    Parameters
    ----------
    uri
        ``s3://bucket/prefix`` or a local directory.
    subdir
        Path within the asset holding CCF-space SWCs. Pass None when `uri`
        already points at a directory of SWC files.
    unsigned
        Use anonymous S3 access, appropriate for ``aind-open-data``.
    """
    if not uri.startswith("s3://"):
        root = Path(uri).expanduser()
        if not root.exists():
            raise FileNotFoundError(f"{root} does not exist")
        inner = _swc_dir(root, subdir)
        files = sorted(inner.rglob("*.swc"))
        if not files:
            raise FileNotFoundError(f"no .swc files under {inner}")
        return Source(uri=str(root), local=inner, files=files)

    parsed = urlparse(uri)
    bucket, prefix = parsed.netloc, parsed.path.lstrip("/").rstrip("/")
    if subdir and not prefix.endswith(subdir):
        prefix = f"{prefix}/{subdir}"
    # S3 listing is already prefix-scoped, so the coordinate-space ambiguity
    # above cannot arise unless the prefix itself is too broad
    dest = Path(dest) if dest else atlas.cache_dir() / "assets" / bucket / prefix
    dest.mkdir(parents=True, exist_ok=True)

    files = _sync(bucket, prefix, dest, unsigned)
    if not files:
        raise FileNotFoundError(f"no .swc files under s3://{bucket}/{prefix}")
    return Source(uri=uri, local=dest, files=files)


def _swc_dir(root: Path, subdir: str | None) -> Path:
    """Find the one directory of SWCs under `root`, or refuse to guess.

    A processed reconstruction asset carries the same cells in several
    coordinate spaces -- `refinement/raw`, `refinement/final-world`,
    `alignment/aligned_swcs` and so on -- and only the CCF-space copy belongs in
    a CCF render. An earlier version fell back to a recursive search whenever
    the configured subdirectory missed, which silently merged all of them: every
    cell was drawn seven times, twice outside the brain, and the run still
    exited 0. So ambiguity is now an error rather than a guess.
    """
    candidates = [subdir] if subdir else []
    candidates += [a for a in SWC_SUBDIR_ALIASES if a != subdir]
    for candidate in candidates:
        if candidate and (root / candidate).is_dir():
            return root / candidate

    holders = sorted({p.parent for p in root.rglob("*.swc")})
    if not holders:
        raise FileNotFoundError(f"no .swc files under {root}")
    if len(holders) == 1:
        return holders[0]

    listed = "\n  ".join(str(h.relative_to(root)) for h in holders)
    raise ValueError(
        f"{root.name} holds .swc files in {len(holders)} directories, which are "
        f"usually the same cells in different coordinate spaces:\n  {listed}\n"
        "Rendering them together would place cells outside the brain. Pass the "
        "CCF-space one explicitly, e.g. --subdir "
        "final/ccf_space_reconstructions/swcs")


def _sync(bucket: str, prefix: str, dest: Path, unsigned: bool) -> list[Path]:
    """Download every ``.swc`` under `prefix`, skipping ones already present."""
    import boto3
    from botocore import UNSIGNED
    from botocore.config import Config

    client = boto3.client("s3", config=Config(signature_version=UNSIGNED)) if unsigned \
        else boto3.client("s3")
    out: list[Path] = []
    pages = client.get_paginator("list_objects_v2").paginate(Bucket=bucket, Prefix=prefix)
    for page in pages:
        for obj in page.get("Contents", []):
            key = obj["Key"]
            if not key.endswith(".swc"):
                continue
            local = dest / Path(key).name
            if not local.exists() or local.stat().st_size != obj["Size"]:
                client.download_file(bucket, key, str(local))
            out.append(local)
    return sorted(out)
